#pragma config(Motor,  motor1,          rightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor4,          rightArm,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          leftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor10,         leftArm,       tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task DriveBase(){
	while(true){
		tankControl(ChD, ChA, 10);
	}
}

task ArmMovement(){
	while(true){
		armControl(rightArm,BtnRUp, BtnRDown);
		armControl(leftArm, BtnRDown, BtnRUp);
	}
}

task main()
{
	startTask(DriveBase);
	startTask(ArmMovement);
	while(true){
		displayTextLine(line1, "Ky Clawbot");
	}
}
