#pragma config(Sensor, port3,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port7,  BumpBottom,     sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          leftArm,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          sideDrive,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         rightArm,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Ky Robot Celebratory Dance
void ClapClaw(int times){
	repeat(times){
		moveMotor(clawMotor, 0.2, rotations, 100);
		moveMotor(clawMotor, -0.2, rotations, 100);
	}
}

void LiftArm(int Direction){
		moveMotorTarget(leftArm, Direction*400, 100);
		moveMotorTarget(rightArm, Direction*400, 100);
}

task main()
{
	while(true){
		setTouchLEDColor(touchLED, colorRed);
		ClapClaw(2);
		LiftArm(1);
		setTouchLEDColor(touchLED, colorViolet);
		turnRight(0.35, rotations, 100);
		ClapClaw(3);
		turnLeft(0.7, rotations, 100);
		ClapClaw(2);
		turnRight(0.35, rotations, 100);
		LiftArm(-1);
		ClapClaw(1);
		playSound(soundTada);
	}
}
