#pragma config(Sensor, port2,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  touchLED,       sensorVexIQ_LED)
#pragma config(Motor,  motor1,          leftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          leftArm,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          hookMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         rightArm,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         sideDrive,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void PickUpLeftYellowHub(){
	// Lift arm to prepare to pick yellow hub
	moveMotorTarget(leftArm, 1000, 100);
	moveMotorTarget(rightArm, 1000, 100);
	// Move sideways to align with the yellow hub
	forward(0.1, rotations, 100);
	moveMotor(sideDrive, 1.85, rotations, 100);
	// Move forward and pick up yellow hub
	waitUntilMotorMoveComplete(leftArm);
	forward(1, rotations, 100);
	moveMotorTarget(leftArm, 225, 100);
	moveMotorTarget(rightArm, 225, 100);
	waitUntilMotorMoveComplete(rightArm);
	// Back up
	backward(1, seconds, 100);
	moveMotorTarget(leftArm, -645, 100);
	moveMotorTarget(rightArm, -645, 100);
	waitUntilMotorMoveComplete(rightArm);
	// Turn left
	turnLeft(320, degrees, 50);
	//Re-align with wall
	moveMotor(sideDrive, 1, seconds, 100);
}

void move3OrangeHubsTo2x2(){
	// Move forward, turn, then prepare to push orange hubs
	forward(1, rotations);
	moveMotor(sideDrive, -0.8, rotations, 100);
	moveMotor(leftDrive, 270, degrees, 100);
	// Go forward and group hubs
	forward(1.5, rotations, 100);
	turnRight(175, degrees, 50);
	// Go forward and push hubs against wall
	forward(1.5, rotations, 100);
	moveMotor(rightDrive, 360, degrees, 100);
	// Move forward to score
	forward(1, rotations, 100);
	// Back up and go forward to push hubs agianst the wall
	backward(1, rotations, 100);
	moveMotor(rightDrive, 0.5, rotations, 100);
	if(getGyroDegrees(gyroSensor) < 90){
		setMotor(rightDrive, 20);
		setMotor(leftDrive, -20);
		waitUntil(getGyroDegrees(gyroSensor) == 90);
		stopMultipleMotors(leftDrive, rightDrive);
	}
	backward(2, rotations, 100);
	// Move sideways and align to the wall
	moveMotor(sideDrive, 2, seconds, -100);
	// Push hubs into sccoring zone
	forward(1.5, rotations, 50);
	moveMotorTarget(leftArm, -300, 100);
	moveMotorTarget(rightArm, -300, 100);
	waitUntilMotorMoveComplete(leftArm);
	backward(1, rotations, 100);
}

void PickUpRightYellowHub(){
	// Lift arm to prepare to pick yellow hub
	moveMotorTarget(leftArm, 720, 100);
	moveMotorTarget(rightArm, 720, 100);
	// Move sideways to align with the yellow hub
	forward(0.1, rotations, 100);
	moveMotor(sideDrive, 1.85, rotations, -100);
	// Move forward and pick up yellow hub
	waitUntilMotorMoveComplete(leftArm);
	forward(1, rotations, 100);
	moveMotorTarget(leftArm, 225, 100);
	moveMotorTarget(rightArm, 225, 100);
	waitUntilMotorMoveComplete(rightArm);
	// Back up
	backward(1, seconds, 100);
	moveMotorTarget(leftArm, -645, 100);
	moveMotorTarget(rightArm, -645, 100);
	waitUntilMotorMoveComplete(rightArm);
	// Prepare to hook 2 hubs
	forward(0.1, rotations, 50);
	moveMotor(sideDrive, 1.35, rotations);
	backward(1, seconds);
}

void Hook2UHubs(){
	forward(2.5, rotations, 100);
	turnLeft(0.35, rotations, 50);
	turnRight(0.35, rotations, 50);
	forward(1, seconds, 100);
	backward(0.2, rotations, 20);
	moveMotor(hookMotor, 0.6, rotations, -50);
	backward(3.5, rotations, 50);
	turnRight(320, degrees, 50);
	moveMotor(sideDrive, 2, seconds, -100);
	forward(0.2, rotations, 100);
	backward(0.2, rotations, 100);
	wait(1, seconds);
	moveMotor(sideDrive, 0.1, rotations, 50);
}

void Pull2HubsInto1x4(){
	backward(5, rotations);
	moveMotor(sideDrive, 1, rotations, 100);
	turnRight(320, degrees, 50);
	moveMotor(sideDrive, 2, rotations, -100);
	forward(3, seconds, 50);
	moveMotor(hookMotor, 0.6, rotations, 50);
	moveMotorTarget(leftArm, -300, 100);
	moveMotorTarget(rightArm, -300, 100);
	backward(1, rotations, 100);
}

void HangOnBar(){
	moveMotorTarget(leftArm, 945, 100);
	moveMotorTarget(rightArm, 945, 100);
	moveMotor(sideDrive, 0.3, rotations, -100);
	forward(2.5, rotations, 100);
	moveMotorTarget(leftArm, -645, 100);
	moveMotorTarget(rightArm, -645, 100);
}

//* Main Task *//
task main()
{
	wait(1, seconds);
	resetGyro(gyroSensor);
	wait(1, seconds);
	setTouchLEDColor(touchLED, colorViolet);
	waitUntil(getTouchLEDValue(touchLED) == true);
	PickUpLeftYellowHub();
	move3OrangeHubsTo2x2();
	setTouchLEDColor(touchLED, colorGreen);
	waitUntil(getTouchLEDValue(touchLED) == true);
	PickUpRightYellowHub();
	Hook2UHubs();
	Pull2HubsInto1x4();
	setTouchLEDColor(touchLED, colorBlue);
}
