#pragma config(Sensor, port2,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port3,  ArmBumper,      sensorVexIQ_Touch)
#pragma config(Sensor, port7,  touchLED,       sensorVexIQ_LED)
#pragma config(Motor,  motor1,          leftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          leftArm,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          sideDrive,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         rightArm,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/**********************************/
/** Movement + Turning Functions **/
/**********************************/

// Turn Right 90 Degrees
void Turn90Right(){
	turnRight(310, degrees, 100);
}

// Turn Left 90 Degrees
void Turn90Left(){
	turnLeft(330, degrees, 100);
}

// Turn 180 Degrees
void Turn180(){
	turnRight(620, degrees, 100);
}

void WaitLED(){
	waitUntil(getTouchLEDValue(touchLED) == true);
}

void MoveArm(int EncoderDistance){
	resetMotorEncoder(leftArm);
	resetMotorEncoder(rightArm);
	setMotor(leftArm);
	setMotor(rightArm);
	waitUntil(getMotorEncoder(leftArm) == EncoderDistance);
	stopMultipleMotors(leftArm, rightArm);
}

void lowerArmUntilBumperPressed(){
	// Set Motors to run until bumper pressed
	if(getBumperValue(ArmBumper) == false){
		setMotor(leftArm, -100);
		setMotor(rightArm, -100);
		waitUntil(getBumperValue(ArmBumper) == true);
		stopMultipleMotors(leftArm, rightArm);
	}
}

/**********************/
/** Function Library **/
/**********************/

void PickUpLeftYellowHub(){
	// Lift arm to prepare to pick yellow hub
	moveMotorTarget(leftArm, 990, 100);
	moveMotorTarget(rightArm, 990, 100);
	wait(1, seconds);
	// Move sideways to align with the yellow hub
	forward(0.1, rotations, 100);
	moveMotor(sideDrive, 1.8, rotations, 100);
	// Move forward and pick up yellow hub
	backward(1, seconds, 100);
	waitUntilMotorMoveComplete(leftArm);
	forward(0.8, rotations, 100);
	moveMotor(clawMotor, 0.5, seconds, -100);
	moveMotorTarget(leftArm, 175, 100);
	moveMotorTarget(rightArm, 175, 100);
	waitUntilMotorMoveComplete(rightArm);
	// Back up and turn
	backward(0.8, seconds, 100);
	Turn90Left();
	// Re-align with wall
	moveMotor(sideDrive, 1, seconds, 100);
}

void PickUpRightYellowHub(){
	// Lift arm to prepare to pick yellow hub
	moveMotorTarget(leftArm, 650, 100);
	moveMotorTarget(rightArm, 650, 100);
	wait(1, seconds);
	// Move sideways to align with the yellow hub
	forward(0.1, rotations, 100);
	moveMotor(sideDrive, 1.8, rotations, -100);
	// Move forward and pick up yellow hub
	backward(1, seconds, 100);
	waitUntilMotorMoveComplete(leftArm);
	forward(0.8, rotations, 100);
	moveMotor(clawMotor, 0.5, seconds, -100);
	moveMotorTarget(leftArm, 175, 100);
	moveMotorTarget(rightArm, 175, 100);
	waitUntilMotorMoveComplete(rightArm);
	// Back up and turn
	backward(0.8, seconds, 100);
	Turn90Left();
	// Re-align with wall
	moveMotor(sideDrive, 1, seconds, 100);
}

void move3OrangeHubsTo2x2(){
	// Move forward, turn, then prepare to push orange hubs
	forward(1, rotations);
	moveMotor(sideDrive, -0.8, rotations, 100);
	moveMotor(leftDrive, 270, degrees, 100);
	// Go forward and group hubs
	forward(1.5, rotations, 100);
	turnRight(175, degrees, 50);
	// Go forward and push hubs against wall
	forward(1.75, rotations, 30);
	moveMotor(rightDrive, 360, degrees, 100);
	// Move forward to score
	forward(1, seconds, 100);
	// Back up and go forward to push hubs agianst the wall
	backward(1, rotations, 100);
	moveMotor(rightDrive, 0.5, rotations, 100);
	wait(2, seconds);
	if(getGyroDegrees(gyroSensor) < 90){
		setMotor(rightDrive, 20);
		setMotor(leftDrive, -20);
		waitUntil(getGyroDegrees(gyroSensor) == 90);
		stopMultipleMotors(leftDrive, rightDrive);
	}
	else if(getGyroDegrees(gyroSensor) < 90){
		setMotor(rightDrive, -20);
		setMotor(leftDrive, 20);
		waitUntil(getGyroDegrees(gyroSensor) == 90);
		stopMultipleMotors(leftDrive, rightDrive);
	}
	backward(2, rotations, 100);
	// Move sideways and align to the wall
	moveMotor(sideDrive, 2, seconds, -100);
	// Push hubs into sccoring zone
	forward(2, rotations, 100);
	moveMotorTarget(leftArm, -825, 100);
	moveMotorTarget(rightArm, -825, 100);
	waitUntilMotorMoveComplete(leftArm);
	moveMotor(clawMotor, 1, seconds, 100);
	backward(1, rotations, 100);
}

void KnockOffRightHub(){
	// Lift arm to prepare to pick yellow hub
	moveMotorTarget(leftArm, 800, 100);
	moveMotorTarget(rightArm, 800, 100);
	wait(1, seconds);
	// Move sideways to align with the yellow hub
	forward(0.1, rotations, 100);
	moveMotor(sideDrive, -2, rotations, 100);
	// Move forward and knock off yellow hub
	backward(1, seconds, 100);
	waitUntilMotorMoveComplete(leftArm);
	forward(1, seconds, 100);
}

void ScoreYellowHub(){
	// Move forward
	forward(6, rotations, 100);
	// Drop Hub
	moveMotorTarget(leftArm, -1165, 100);
	moveMotorTarget(rightArm, -1165, 100);
	waitUntilMotorMoveComplete(leftArm);
	// Open Claw
	moveMotor(clawMotor, 0.5, seconds, 100);
	// Backup
	backward(0.5, rotations, 100);
	// Lift arm
	moveMotorTarget(leftArm, 500, 100);
	moveMotorTarget(rightArm, 500, 100);
	// Move sideways
	moveMotor(sideDrive, -1, rotations, 100);
	// Move forward
	forward(1, rotations, 100);
	moveMotor(sideDrive, 0.5, rotations, 100);
}

void MoveScoringZone(){
	moveMotor(sideDrive, 0.5, rotations, 100);
	forward(2, rotations, 100);
}

//* Main Task *//
task main()
{
	resetGyro(gyroSensor);
	setTouchLEDColor(touchLED, colorViolet);
	waitUntil(getTouchLEDValue(touchLED) == true);
	PickUpLeftYellowHub();
	move3OrangeHubsTo2x2();
	moveMotor(sideDrive, 2, seconds, 100);
	waitUntil(getTouchLEDValue(touchLED) == true);
	PickUpRightYellowHub();
	ScoreYellowHub();
	// Go to scoring zone
	while(true){
		waitUntil(getTouchLEDValue(touchLED) == true);
		MoveScoringZone();
	}
}
