#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port3,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          leftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          sideDrive,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor9,          hookMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         rightArm,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         leftArm,       tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// 0 = Regular | 1 = 50%
int DriveBaseSpeedMode = 0;

// Task to syncronize arm motorsd
task ArmMovement(){
	while(true){
		armControl(leftArm, BtnRUp, BtnRDown);
		armControl(rightArm, BtnRUp, BtnRDown);
	}
}

// Task to move claw
task HookMovement(){
	while(true){
		armControl(hookMotor, BtnEUp, BtnFUp);
	}
}

task BaseControl(){
	while(true){
		if(DriveBaseSpeedMode == 0){
			setJoystickScale(200);
			tankControl(ChD, ChA, 10);
			armControl(sideDrive, BtnLUp, BtnLDown);
		}
		else if(DriveBaseSpeedMode == 1){
			setJoystickScale(65);
			tankControl(ChD, ChA, 10);
			armControl(sideDrive, BtnLUp, BtnLDown);
		}
	}
}


task SideFunctions(){
	while(true){
		if(vexRT[BtnFUp] == true && vexRT[BtnEUp] == true){
		// Go under Bar
			stopTask(ArmMovement);
			setMotorTarget(leftArm, 500, 100);
			setMotorTarget(rightArm, 500, 100);
			waitUntilMotorMoveComplete(leftArm);
			startTask(ArmMovement);
		}

		else if(vexRT[BtnEDown] == true){
			// Pick Yellow Hub
			stopTask(ArmMovement);
			setMotorTarget(leftArm, 1025, 100);
			setMotorTarget(rightArm, 1025, 100);
			waitUntilMotorMoveComplete(leftArm);
			startTask(ArmMovement);
		}

	}
}

// Function to stop/start tasks
void startLimbTasks(){
	startTask(HookMovement);
	startTask(ArmMovement);
}



// Task for special commands
task main(){
	resetMotorEncoder(rightArm);
	resetMotorEncoder(leftArm);
	startTask(BaseControl);
	startTask(SideFunctions);
	startLimbTasks();
	setTouchLEDColor(touchLED, colorRed);
	while(true){
		// Display program and run Claw Control
		displayTextLine(line1, "Avalon TeleOp");
		if(vexRT[BtnFDown] == true && DriveBaseSpeedMode == 1){
			DriveBaseSpeedMode = 0;
			setTouchLEDColor(touchLED, colorRed);
			sleep(300);
		}
		if(vexRT[BtnFDown] == true && DriveBaseSpeedMode == 0){
			DriveBaseSpeedMode = 1;
			setTouchLEDColor(touchLED, colorBlue);
			sleep(300);
		}
	}
}
