#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port3,  bumpSensor,     sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftDrive,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor4,          sideDrive,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightDrive,    tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor10,         rightArm,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         hookMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         leftArm,       tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// 0 = Regular | 1 = 50%
int DriveBaseSpeedMode = 0;



// Task to syncronize arm motorsd
task ArmMovement(){
	while(true){
		armControl(leftArm, BtnRDown, BtnRUp);
		armControl(rightArm, BtnRDown, BtnRUp);
	}
}

// Task to move claw
task HookMovement(){
	while(true){
		armControl(hookMotor, BtnFUp, BtnEUp);
	}
}

task BaseControl(){
	while(true){
		if(DriveBaseSpeedMode == 0){
			setJoystickScale(100);
			tankControl(ChD, ChA, 10);
			armControl(sideDrive, BtnLUp, BtnLDown);
		}
		else if(DriveBaseSpeedMode == 1){
			setJoystickScale(50);
			tankControl(ChD, ChA, 10);
			armControl(sideDrive, BtnLUp, BtnLDown);
		}
	}
}


task SideFunctions(){
	while(true){
		if(vexRT[BtnFUp] == true && vexRT[BtnEUp] == true){
			stopTask(ArmMovement);
			setMotorTarget(leftArm, -1200, 100);
			setMotorTarget(rightArm, -1200, 100);
			waitUntilMotorMoveComplete(leftArm);
			startTask(ArmMovement);
			waitUntil(vexRT[BtnFUp] == true && vexRT[BtnEUp] == true);
			stopTask(ArmMovement);
			setMotorTarget(leftArm, -65, 100);
			setMotorTarget(rightArm, -65, 100);
			waitUntilMotorMoveComplete(leftArm);
			startTask(ArmMovement);
		}

		else if(vexRT[BtnEDown] == true){
			stopTask(ArmMovement);
			setMotorTarget(leftArm, -800, 100);
			setMotorTarget(rightArm, -800, 100);
			waitUntilMotorMoveComplete(leftArm);
			startTask(ArmMovement);
		}
	}
}

// Function to stop/start tasks
void startLimbTasks(){
	startTask(HookMovement);
	startTask(ArmMovement);
}



// Task for special commands

task main(){
	// Start tasks
	setMotor(rightArm, 50);
	setMotor(leftArm, 50);
	waitUntil(getBumperValue(bumpSensor) == true);
	stopMultipleMotors(leftArm, rightArm);
	resetMotorEncoder(leftArm);
	resetMotorEncoder(rightArm);
	startTask(BaseControl);
	startTask(SideFunctions);
	startLimbTasks();
	setTouchLEDColor(touchLED, colorRed);
	while(true){
		// Display program and run Claw Control
		displayTextLine(line1, "Elysium TeleOp");
		if(vexRT[BtnFDown] == true && DriveBaseSpeedMode == 1){
			DriveBaseSpeedMode = 0;
			setTouchLEDColor(touchLED, colorRed);
			sleep(300);
		}
		if(vexRT[BtnFDown] == true && DriveBaseSpeedMode == 0){
			DriveBaseSpeedMode = 1;
			setTouchLEDColor(touchLED, colorBlue);
			sleep(300);
		}
	}
}
